###> version docker ###
version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mysql
    container_name: mysql_symfony_agence
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfony_agence
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  www:
    build: php
    container_name: www_symfony_agence
    ports:
      - 8741:80
    volumes:
      - ./php/vhosts:/etc/apache2//sites-enabled
      - ./:/var/www
    networks:
      - dev


volumes:
###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###

networks:
  dev: